### ISSUE TITLE
Support large files

### ISSUE THREAD

**Issue by andriygm** [yurique/embedded-files#67]
Currently, large files throw a `java.io.UTFDataFormatException: encoded string too long` when parsed using `FileAsString`. We may want to provide a `FileAsCharArray`, or a `FileAsStringArray` accepting a delimiter for splitting the string.

**Comment by yurique** [comment]
@andriygm is this still something you'd want solved? :)

**Comment by andriygm** [comment]
I think this may be an artifact of Scala.js compilation and not embedded-files. I'd have to test some more to make sure.
